---
- name: install haproxy loadbalncer
  yum:
    name: haproxy
    state: latest

- name: start and enable haproxy at reboot 
  service:
    name: haproxy 
    state: started
    enabled: yes

- name: copy haproxy config to destination directory
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy



